create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where admin_users.user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "Admins can read admin users" on public.admin_users;
create policy "Admins can read admin users"
on public.admin_users
for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can manage admin users" on public.admin_users;
create policy "Admins can manage admin users"
on public.admin_users
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create table if not exists public.admin_questions (
  id integer generated by default as identity (start with 100001) primary key,
  topic_id text not null,
  topic text not null,
  difficulty text not null check (difficulty in ('easy', 'medium', 'hard')),
  type text not null check (type in ('fact', 'scenario', 'truefalse')),
  question text not null check (length(trim(question)) > 0),
  options text[] not null check (array_length(options, 1) between 2 and 4),
  correct_answer integer not null check (correct_answer >= 0),
  explanation text not null check (length(trim(explanation)) > 0),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_questions_correct_answer_in_options
    check (correct_answer < array_length(options, 1))
);

create index if not exists admin_questions_topic_id_idx
on public.admin_questions (topic_id);

create index if not exists admin_questions_type_idx
on public.admin_questions (type);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists admin_questions_set_updated_at on public.admin_questions;
create trigger admin_questions_set_updated_at
before update on public.admin_questions
for each row
execute function public.set_updated_at();

alter table public.admin_questions enable row level security;

grant select on public.admin_questions to anon, authenticated;
grant insert, update, delete on public.admin_questions to authenticated;
grant usage, select on sequence public.admin_questions_id_seq to authenticated;

drop policy if exists "Anyone can read admin questions" on public.admin_questions;
create policy "Anyone can read admin questions"
on public.admin_questions
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can create admin questions" on public.admin_questions;
create policy "Admins can create admin questions"
on public.admin_questions
for insert
to authenticated
with check (public.is_admin() and created_by = auth.uid());

drop policy if exists "Admins can update admin questions" on public.admin_questions;
create policy "Admins can update admin questions"
on public.admin_questions
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete admin questions" on public.admin_questions;
create policy "Admins can delete admin questions"
on public.admin_questions
for delete
to authenticated
using (public.is_admin());
